package org.psug.usi.domain

import org.psug.usi.store._
import com.sleepycat.bind.tuple.{IntegerBinding, StringBinding}
import com.sleepycat.je.{LockMode, DatabaseEntry}

import com.sun.jersey.core.util.Base64

object User{
    def apply(firstName : String, lastName : String, email : String, password : String):User = User( 0, firstName, lastName, email, password )
}

object AuthenticationToken {
  val re = "(\\d+);(.*)".r
  implicit def decrypt(value : String) : AuthenticationToken = Base64.base64Decode(value) match {
    case re(id,email) => AuthenticationToken(Integer.parseInt(id),email)
    case _            => throw new IllegalArgumentException("cannot decode token "+value)
  }

  implicit def encrypt(token : AuthenticationToken) : String = new String(Base64.encode(token.id + ";" + token.email))
}

case class AuthenticationToken(id : Int, email : String)

case class Credentials(email: String, password: String)

case class User( id:Int, firstName:String, lastName:String, email:String, password:String ) extends Data[Int]{
  def storeKey:Int = id
  def copyWithAutoGeneratedId( id:Int ) = User( id, firstName, lastName, email, password )

  /*
    les longueurs min/max sont les suivantes : de 2 à 50 caractères pour nom, prénom, mail et password.
   */
  def isValid = {
    firstName.length >= 2 && firstName.length <= 50 &&
    lastName.length >= 2 && lastName.length <= 50 &&
    email.length >= 2 && email.length <= 50 &&
    password.length >= 2 && password.length <= 50
  }

}

case class PullDataByEmail( email : String ) extends DataRepositoryMessage
case class AuthenticateUser (credentials : Credentials) extends DataRepositoryMessage
case class UserAuthenticated (user : Either[User,String]) extends DataRepositoryMessage

class UserRepository extends BDBDataRepository[User]( "UserRepository" ) {

  override def store( id:Int, in:User ){
    val key = new DatabaseEntry()
    StringBinding.stringToEntry( in.email, key )

    val data = new DatabaseEntry()
    IntegerBinding.intToEntry( id, data )
    database.put( null, key, data )

    super.store( id, in )
  }

  def idByEmail( email:String ) = {
    val key = new DatabaseEntry()
    StringBinding.stringToEntry( email, key )

    val data = new DatabaseEntry()
    database.get( null, key, data, LockMode.READ_UNCOMMITTED )
    if( data.getData != null ){
      Some( IntegerBinding.entryToInt(data ) )
    }
    else None
  }


  /*
    si un utilisateur ayant la même adresse mail existe déjà, une erreur est retournée.
   */
  override protected def checkConstraint( user:User )={
    if(!user.isValid)
      Some("User does not respect fields format constraint")
    else if(!idByEmail( user.email ).isEmpty)
      Some("A user with same email as "+ user.email +" is registered")
    else
      None
  }

  def lookupUser(email : String) : DataPulled[Int] =
    DataPulled[Int]( for(id   <- idByEmail( email );
                    user <- load( id )) yield user)

  override def handleMessage( any:Any )={
    any match {
      case PullDataByEmail( email ) =>
        lookupUser(email)
      case AuthenticateUser(credentials) =>
        lookupUser(credentials.email) match {
          case DataPulled(Some(user))  =>  {
            if(user.asInstanceOf[User].password == credentials.password) {
              UserAuthenticated(Left(user.asInstanceOf[User]))
            } else
              UserAuthenticated(Right("invalid credentials for user " + credentials.email))
          }
          case DataPulled(None)       =>
              UserAuthenticated(Right("invalid credentials for user " + credentials.email))
        }
      case _ => super.handleMessage( any )
    }
  }
}

